import type { PathProps, SkDOM, GroupProps, ImageProps, BlurImageFilterProps, MatrixColorFilterProps, CircleProps, BlurMaskFilterProps, LinearGradientProps, PaintProps, ShaderProps, ImageShaderProps, CustomDrawingNodeProps, LineProps, OvalProps, PatchProps, PointsProps, RectProps, RoundedRectProps, VerticesProps, TextProps, DiffRectProps, OffsetImageFilterProps, BlendColorFilterProps, TextPathProps, TextBlobProps, GlyphsProps, TwoPointConicalGradientProps, TurbulenceProps, SweepGradientProps, RadialGradientProps, FractalNoiseProps, ColorProps, PictureProps, ImageSVGProps, LerpColorFilterProps, DrawingNodeProps, BoxProps, BoxShadowProps, ChildrenProps } from "../types";
import type { BlendImageFilterProps, BlendProps, DisplacementMapImageFilterProps, DropShadowImageFilterProps, MorphologyImageFilterProps, RuntimeShaderImageFilterProps } from "../types/ImageFilters";
import type { CornerPathEffectProps, DashPathEffectProps, DiscretePathEffectProps, Line2DPathEffectProps, Path1DPathEffectProps, Path2DPathEffectProps } from "../types/PathEffects";
import { FillNode, ImageNode, CircleNode, PathNode, LineNode, PatchNode, PointsNode, RectNode, RRectNode, VerticesNode, TextNode, OvalNode, CustomDrawingNode, TextPathNode, TextBlobNode, GlyphsNode, DiffRectNode, PictureNode, ImageSVGNode, BackdropFilterNode, BoxNode, BoxShadowNode } from "./drawings";
import { BlendImageFilterNode, BlurImageFilterNode, BlurMaskFilterNode, DisplacementMapImageFilterNode, DropShadowImageFilterNode, OffsetImageFilterNode, RuntimeShaderImageFilterNode, CornerPathEffectNode, DiscretePathEffectNode, DashPathEffectNode, Path1DPathEffectNode, Path2DPathEffectNode, SumPathEffectNode, Line2DPathEffectNode, BlendNode } from "./paint";
import { MatrixColorFilterNode, LumaColorFilterNode, LinearToSRGBGammaColorFilterNode, SRGBToLinearGammaColorFilterNode, BlendColorFilterNode, LerpColorFilterNode } from "./paint/ColorFilters";
import { LinearGradientNode, ShaderNode, ImageShaderNode, TwoPointConicalGradientNode, TurbulenceNode, SweepGradientNode, RadialGradientNode, FractalNoiseNode, ColorNode } from "./paint/Shaders";
import { MorphologyImageFilterNode } from "./paint/ImageFilters";
import { GroupNode } from "./GroupNode";
import { PaintNode } from "./PaintNode";
import type { NodeContext } from "./Node";
export declare class JsiSkDOM implements SkDOM {
    private ctx;
    constructor(ctx: NodeContext);
    Group(props?: GroupProps): GroupNode;
    Paint(props: PaintProps): PaintNode;
    Fill(props?: DrawingNodeProps): FillNode;
    Image(props: ImageProps): ImageNode;
    Circle(props: CircleProps): CircleNode;
    Path(props: PathProps): PathNode;
    CustomDrawing(props: CustomDrawingNodeProps): CustomDrawingNode;
    Line(props: LineProps): LineNode;
    Oval(props: OvalProps): OvalNode;
    Patch(props: PatchProps): PatchNode;
    Points(props: PointsProps): PointsNode;
    Rect(props: RectProps): RectNode;
    RRect(props: RoundedRectProps): RRectNode;
    Vertices(props: VerticesProps): VerticesNode;
    Text(props: TextProps): TextNode;
    TextPath(props: TextPathProps): TextPathNode;
    TextBlob(props: TextBlobProps): TextBlobNode;
    Glyphs(props: GlyphsProps): GlyphsNode;
    DiffRect(props: DiffRectProps): DiffRectNode;
    Picture(props: PictureProps): PictureNode;
    ImageSVG(props: ImageSVGProps): ImageSVGNode;
    BlurMaskFilter(props: BlurMaskFilterProps): BlurMaskFilterNode;
    BlendImageFilter(props: BlendImageFilterProps): BlendImageFilterNode;
    DropShadowImageFilter(props: DropShadowImageFilterProps): DropShadowImageFilterNode;
    DisplacementMapImageFilter(props: DisplacementMapImageFilterProps): DisplacementMapImageFilterNode;
    BlurImageFilter(props: BlurImageFilterProps): BlurImageFilterNode;
    OffsetImageFilter(props: OffsetImageFilterProps): OffsetImageFilterNode;
    MorphologyImageFilter(props: MorphologyImageFilterProps): MorphologyImageFilterNode;
    RuntimeShaderImageFilter(props: RuntimeShaderImageFilterProps): RuntimeShaderImageFilterNode;
    MatrixColorFilter(props: MatrixColorFilterProps): MatrixColorFilterNode;
    BlendColorFilter(props: BlendColorFilterProps): BlendColorFilterNode;
    LumaColorFilter(): LumaColorFilterNode;
    LinearToSRGBGammaColorFilter(): LinearToSRGBGammaColorFilterNode;
    SRGBToLinearGammaColorFilter(): SRGBToLinearGammaColorFilterNode;
    LerpColorFilter(props: LerpColorFilterProps): LerpColorFilterNode;
    Shader(props: ShaderProps): ShaderNode;
    ImageShader(props: ImageShaderProps): ImageShaderNode;
    ColorShader(props: ColorProps): ColorNode;
    SweepGradient(props: SweepGradientProps): SweepGradientNode;
    Turbulence(props: TurbulenceProps): TurbulenceNode;
    FractalNoise(props: FractalNoiseProps): FractalNoiseNode;
    LinearGradient(props: LinearGradientProps): LinearGradientNode;
    RadialGradient(props: RadialGradientProps): RadialGradientNode;
    TwoPointConicalGradient(props: TwoPointConicalGradientProps): TwoPointConicalGradientNode;
    CornerPathEffect(props: CornerPathEffectProps): CornerPathEffectNode;
    DiscretePathEffect(props: DiscretePathEffectProps): DiscretePathEffectNode;
    DashPathEffect(props: DashPathEffectProps): DashPathEffectNode;
    Path1DPathEffect(props: Path1DPathEffectProps): Path1DPathEffectNode;
    Path2DPathEffect(props: Path2DPathEffectProps): Path2DPathEffectNode;
    SumPathEffect(): SumPathEffectNode;
    Line2DPathEffect(props: Line2DPathEffectProps): Line2DPathEffectNode;
    Blend(props: BlendProps): BlendNode;
    BackdropFilter(props: ChildrenProps): BackdropFilterNode;
    Box(props: BoxProps): BoxNode;
    BoxShadow(props: BoxShadowProps): BoxShadowNode;
}
